version: '2'

networks:
  underground-river:

services:
  postgresql:
    image: bitnami/postgresql:13
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=blasement
      - POSTGRESQL_PASSWORD=welcome
      - POSTGRESQL_DATABASE=blasement
    networks:
      - underground-river
  blasement:
    image: undermybrella/the-blasement:latest
    networks:
      - underground-river
volumes:
  postgresql_data:
    driver: local